

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amirhossein zamani
 */
public class DeleteAccount extends javax.swing.JFrame {

    /**
     * Creates new form DeleteAccount
     */
    public DeleteAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Delete Account");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 250));

        buttonDelete.setBackground(new java.awt.Color(255, 51, 51));
        buttonDelete.setText("Delete that");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Are you sure to delete your account?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(buttonDelete)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(buttonDelete)
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        
        try {
             
            //delete from users
            Class.forName("com.mysql.jdbc.Driver");             
            Connection connector = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/instagram?autoReconnect=true&useSSL=false", "root", ""); 
            String sqlOrder = "DELETE FROM user WHERE username = ?";
            PreparedStatement preparedStatement = connector.prepareStatement(sqlOrder);
            preparedStatement.setString(1, Login.usernameHelper); //person page
            preparedStatement.executeUpdate();
            
            
            //delete from pv
            String sqlOrder1 = "DELETE FROM chat WHERE usernameSender = ? OR usernameReceiver = ?";
            PreparedStatement preparedStatement1 = connector.prepareStatement(sqlOrder1);
            preparedStatement1.setString(1, Login.usernameHelper);
            preparedStatement1.setString(2, Login.usernameHelper);
            preparedStatement1.executeUpdate();
            
            
            //delete from posts
            String sqlOrder2 = "DELETE FROM post WHERE username = ?";
            PreparedStatement preparedStatement2 = connector.prepareStatement(sqlOrder2);
            preparedStatement2.setString(1, Login.usernameHelper);
            preparedStatement2.executeUpdate();
            
            
            //delete likes
            String sqlOrder3 = "DELETE FROM likepost WHERE usernameLiker = ? OR usernameLiked = ?";
            PreparedStatement preparedStatement3 = connector.prepareStatement(sqlOrder3);
            preparedStatement3.setString(1, Login.usernameHelper);
            preparedStatement3.setString(2, Login.usernameHelper);
            preparedStatement3.executeUpdate();
            
            
            //delete follow
            String sqlOrder4 = "DELETE FROM follow WHERE usernameno1 = ? OR usernameno2 = ?";
            PreparedStatement preparedStatement4 = connector.prepareStatement(sqlOrder4);
            preparedStatement4.setString(1, Login.usernameHelper);
            preparedStatement4.setString(2, Login.usernameHelper);
            preparedStatement4.executeUpdate();
            
            
            //delete comment
            String sqlOrder5 = "DELETE FROM comments WHERE usernameCommenter = ? OR usernamePoster = ?";
            PreparedStatement preparedStatement5 = connector.prepareStatement(sqlOrder5);
            preparedStatement5.setString(1, Login.usernameHelper);
            preparedStatement5.setString(2, Login.usernameHelper);
            preparedStatement5.executeUpdate();
            

            JOptionPane.showMessageDialog(null, "Your account has been deleted successfully!");
            System.exit(0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!" + e.toString());
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
